# Base image:
FROM ruby:2.3.4

ENV \
    RS_USER="deploy"
# Install dependencies
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main" >> /etc/apt/sources.list.d/pgdg.list
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | \
  apt-key add -
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs postgresql-client-9.6
#node install
RUN set -ex \
  && for key in \
    9554F04D7259F04124DE6B476D5A82AC7E37093B \
    94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
    FD3A5288F042B6850C66B31F09FE44734EB7990E \
    71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
    DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
    B9AE9905FFD7803F25714661B63B535A4C206CA9 \
    C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
    56730D5401028683275BD23C23EFEFE93C4CFFFE \
  ; do \
    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key" || \
    gpg --keyserver pgp.mit.edu --recv-keys "$key" || \
    gpg --keyserver keyserver.pgp.com --recv-keys "$key" ; \
  done

ENV NPM_CONFIG_LOGLEVEL info
ENV NODE_VERSION 7.8.0

RUN curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz" \
  && curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc" \
  && gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc \
  && grep " node-v$NODE_VERSION-linux-x64.tar.xz\$" SHASUMS256.txt | sha256sum -c - \
  && tar -xJf "node-v$NODE_VERSION-linux-x64.tar.xz" -C /usr/local --strip-components=1 \
  && rm "node-v$NODE_VERSION-linux-x64.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt \
  && ln -s /usr/local/bin/node /usr/local/bin/nodejs 
#add work user
RUN useradd \
       --uid 1000 \
       --user-group \
       --shell /bin/bash \
       --create-home \
       --home-dir /home/${RS_USER} \
         deploy
USER ${RS_USER}:${RS_USER}
# Set working directory, where the commands will be ran:
WORKDIR /home/${RS_USER}/web
 
# Gems:
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock 
RUN gem install bundler
RUN bundle install
 
EXPOSE 3000
 
# The default command that gets ran will be to start the Puma server.
CMD bundle exec puma -C config/puma.rb

# Copy the main application.
#COPY . .

USER root
RUN mkdir /home/${RS_USER}/web/tmp && mkdir /home/${RS_USER}/web/tmp/pids
RUN chown -R 1000:1000 /home/${RS_USER}/web

USER ${RS_USER}:${RS_USER}

#move file
#RUN bin/rails assets:precompile

#db
#RUN bin/rails db:migrate && bin/rails db:migrate:status && bin/rails db:seed
#RUN rake db:migrate
#RUN rake db:migrate:status
#RUN rake db:seed

